### ISSUE TITLE
Cannot read property 'on' of undefined when downloading torrents

### ISSUE THREAD

**Issue by TheodoreKrypton** [webtorrent/webtorrent-cli#101]
![image](https://user-images.githubusercontent.com/12686172/59563653-4f6fb000-906f-11e9-9869-1babdae5101a.png)

**Comment by arklochkow** [comment]
I change: 
server.listen(argv.port, initServer)
    .on('error', function (err) {
      if (err.code === 'EADDRINUSE' || err.code === 'EACCES') {
        // If port is taken, pick one a free one automatically
        return server.listen(0, initServer)
      }
      fatalError(err)
    })
to:
server.listen(argv.port, initServer)
from: /usr/local/lib/node_modules/webtorrent-cli/bin/cmd.js

and it worked)

**Comment by DiegoRBaquero** [comment]
`server.listen` returns the server itself which does have .on to listen to events. What am I missing here? server is just created a few lines before

**Comment by Lyken17** [comment]
Thanks @arklochkow ! Your fix works for me.

**Comment by DiegoRBaquero** [comment]
Should be fixed now
