### ISSUE TITLE
Unable to set download destination on windows

### ISSUE THREAD

**Issue by Jelomite** [webtorrent/webtorrent-cli#108]
When I'm downloading a torrent using the following command:

```sh
> webtorrent magnet:?xt=urn:btih:5f4fe04fe53f6601fee1e850aebdce4a4a7f4d27&dn=archlinux-2019.08.01-x86_64.iso&tr=udp://tracker.archlinux.org:6969&tr=http://tracker.archlinux.org:6969/announce -o C:\Users\moshe\Desktop                                                                                                           
```
I expect it to download in C:\Users\moshe\Desktop.
The current behavior is that it ignores the output flag and downloads it to the current directory.

(On Linux it works as expected)

### The magnet link is a download of Arch Linux. This is not a copyright infringement. The Arch Linux project is open source.

**Comment by feross** [comment]
Thanks for the bug report.

**Comment by Jelomite** [comment]
After further inspection of the code, I've found the reason for the bug - there must be quotes before and after the magnet url:
```sh
webtorrent "MAGNET_URL" --<FLAGS>
```

I have no idea why this is inconsistent across the different platforms, but this has nothing to do with webtorrent-cli. This is related to [minimist](https://github.com/substack/minimist) .

I would suggest changing the README to inform others about this issue.

**Comment by iovis** [comment]
Yeah, I have to do the same in mac

**Comment by iovis** [comment]
I think it has to do with magnet links using special characters in bash, like `?`, `&` or `/`

**Comment by feross** [comment]
@iovis Yep, you're right :)
