### ISSUE TITLE
Error raised by cliflix - ReferenceError: URL is not defined

### ISSUE THREAD

**Issue by power-media** [webtorrent/webtorrent-cli#117]
**What version of this package are you using?**
 webtorrent-cli 1.12.3, webtorrent 0.107.16
**What operating system, Node.js, and npm version?**
 node v8.11.1, win32 x64
**What happened?**
Crashed when cliflix used - consistently happens, cliflix is not usable.
**What did you expect to happen?**
See no error, and have cliflix working :)
**Are you willing to submit a pull request to fix this bug?**
No
![Screenshot_2](https://user-images.githubusercontent.com/8167541/66773982-4f19e100-eeb8-11e9-8cae-5a6db2577677.png)

**Comment by alxhotel** [comment]
Upgrade to Node v10 LTS or Node v12, version 8 is not supported.

**Comment by jjdevbiz** [comment]
Using Node v10 LTS worked
