### ISSUE TITLE
Can't install via NPM on Ubuntu

### ISSUE THREAD

**Issue by karthickshiva** [webtorrent/webtorrent-cli#122]
The latest version of webtorrent-cli throws the following error while installing via npm

`
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/feross/http-node.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
`

OS: Ubuntu 18
NodeJS: 12.14.0
NPM: 6.13.4

**Comment by helloitsnaveen** [comment]
Encountering same error on CentOS 8:

`npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/feross/http-node.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
`

OS: CentOS 8
NPM: 6.14.4

**Comment by alxhotel** [comment]
This is probably due to a bug in the package `wrtc` (it should support node `^14.0.0`):

```
npm WARN notsup Unsupported engine for wrtc@0.4.5: wanted: {"node":"^8.11.2 || ^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0"} (current: {"node":"14.5.0","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: wrtc@0.4.5
```

**Comment by alxhotel** [comment]
@karthickshiva @helloitsnaveen please check that `git` is installed in your machines.

Seems like another use had this same issue (webtorrent/webtorrent#1888).

**Comment by alxhotel** [comment]
Closing this. If the issue remains, feel free to reopen it.
