### ISSUE TITLE
Why not switching over to a better argument parser library?

### ISSUE THREAD

**Issue by jamesgeorge007** [webtorrent/webtorrent-cli#123]
**What problem do you want to solve?**
The project as of now makes use of `minimist` for the purpose of argument parsing. One can come across a single source file with bunch of `if-else` statements essentially affecting the DX.

**What do you think is the correct solution to this problem?**
Switch over to a better `argument parser library` which does the job. Thereby we can adopt the principles of modularity making the code-base a lot cleaner. If bundle size is worth concern, [commander.js](https://github.com/tj/commander.js/) would be a great choice .

**Are you willing to submit a pull request to implement this change?**
Ofc :+1:

**Comment by rom1504** [comment]
This is already using minimist

**Comment by jamesgeorge007** [comment]
@rom1504 makes sense?

**Comment by jamesgeorge007** [comment]
https://github.com/webtorrent/webtorrent-cli/blob/36a244877feb1be1244fd015876e92e02592b0a4/bin/cmd.js#L180

`minimist` isn't a fully fledged arg-parser library at-least IMO. As evident from the above code snippet, it requires couple of manual workarounds in-order to get things done. I would say that switching over to something like `commander.js` would make sense here.

**Comment by rom1504** [comment]
You can always try to write a PR with commander.js 
If you find out that it's indeed much better, I can't see why it wouldn't be accepted

**Comment by jamesgeorge007** [comment]
Since this calls for a major refactor, I would like to hear out from other maintainers regarding the same just to ensure my work never goes in vain.

**Comment by jamesgeorge007** [comment]
\cc @feross

**Comment by feross** [comment]
I'm quite happy with `minimist` so I'll close this issue. However, I'm still happy to review PR #144 for it's other changes.
