### ISSUE TITLE
File selection like peerflix

### ISSUE THREAD

**Issue by whtv** [webtorrent/webtorrent-cli#130]
The way I use webtorrent-cli is this: I have a wrapper script  associated with magnet links that runs webtorrent-cli in a terminal. Now this doesn’t work with torrents where I want a specific file. The way peerflix does it (or did, seems obsolete to me now since webtorrent is so much faster!) is an interactive menu for selecting a file, instead of exiting like webtorrent-cli. Unfortunately I’m not capable of helping out in this myself but the code should already pretty much be there in peerflix. I don’t see a downside to it and it might be useful for other people too, no?

**Comment by whtv** [comment]
Actually a simple wrapper script does the job, in case this is not going to be a feature:
```
#!/bin/bash
webtorrent download "$1" -s
read -n 1 -p "File number: " nr
webtorrent download "$@" -s $nr
```

**Comment by feross** [comment]
This is a great feature suggestion. To keep the issue tracker clean, I'm going to close this since there's no bug to fix here. 
If you would like to see it implemented, please send a pull request!
