### ISSUE TITLE
Flag for script-friendly output

### ISSUE THREAD

**Issue by noctuid** [webtorrent/webtorrent-cli#132]
I have an mpv script that uses webtorrent-cli and parses its output (which is somewhat complicated to do, especially because of the colorized output). It would be nice if there was a flag to just output json once as soon as the server is up (no colors) and nothing else. For example, something like this:
```json
{
    "selected": 0,
    "files": [
        {
            "href": "localhost://8000/...",
            "name": "Video name.mkv",
            "path": "/path/to/Video name.mkv"
        },
        ...
    ]
}
```

Edit: In some cases it would actually be useful to keep the normal output as well, so if this could just be output on a single line non-colored once the server is up, that would be good (assuming this is the only case where `{` starts a line). That or if there was a flag to run a command with this as the argument once the server was up.

**Comment by feross** [comment]
If you want to send a PR implementing a `--json` flag, we'd review it 👍 I'm closing this issue since there's no bug to fix here, but feel free to continue discussion! ✨
