### ISSUE TITLE
Cli client donot store file on ubuntu

### ISSUE THREAD

**Issue by Musadiqraees** [webtorrent/webtorrent-cli#136]
There is one issue i need a guidance from you to save time.  my webtorrent cli  download file but dont save it in directory (i have tried giving path with  -o path ).  on my mac it work perfect, file is downloaded and saved in directory but on ubuntu instance its making issue. Please guide me

**Comment by feross** [comment]
It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.
