### ISSUE TITLE
Allow providing additional options to MPV

### ISSUE THREAD

**Issue by JosephKiranBabu** [webtorrent/webtorrent-cli#141]
MPV has some useful options like "--no-video" (for mp3 files) and "--full-screen" which can be used while streaming. Please add support for passing additional options to the media player.

For example, a magnet link to an mp3 file can be streamed as follows, without opening a window.
```
webtorrent "magnet:...." --mpv -- --no-video
```
I borrowed the syntax for mpv options from peerflix.

**Comment by pc00per** [comment]
Is there anyway to use `--ytdlformat=` ?
