### ISSUE TITLE
cli is not opening vlc

### ISSUE THREAD

**Issue by vagharsh** [webtorrent/webtorrent-cli#142]
**What version of this package are you using?**
webtorrent-cli 3.0.6, webtorrent 0.108.6, node v14.5.0, darwin x64, exit 1

**What operating system, Node.js, and npm version?**
Mac OSX 10.15.6 (19G73)

**What happened?**
executed this 
`webtorrent download now-you-see-me.torrent --vlc` and it returned this error
```
Error: Command failed: /Applications/VLC.app/Contents/MacOS/VLC http://localhost:8000/0/Now%20You%20See%20Me%20(2013)%20BDRip%201080p.mkv --play-and-exit --quiet --video-on-top
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `/Applications/VLC.app/Contents/MacOS/VLC http://localhost:8000/0/Now%20You%20See%20Me%20(2013)%20BDRip%201080p.mkv --play-and-exit --quiet --video-on-top'


UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/webtorrent/webtorrent-cli/issues
DEBUG INFO: webtorrent-cli 3.0.6, webtorrent 0.108.6, node v14.5.0, darwin x64, exit 1
```

**What did you expect to happen?**
open vlc but it did not

**Are you willing to submit a pull request to fix this bug?**
yes, i added quotes to the href that is passed to the openPlayer function and it worked

**Comment by alxhotel** [comment]
This bug has been fixed in #138.

It should be working in the next release.

**Comment by raghavprasad13** [comment]
When the streaming options are used with `webtorrent`, such as `--vlc` and `--chromecast`, where is that data stored? Where is the default write location for it?

**Comment by alxhotel** [comment]
Hi @vagharsh, thanks for reporting this.

This issue should already be fixed in `3.0.7`.

If this is not the case, please reopen this issue.

**Comment by alxhotel** [comment]
> When the streaming options are used with `webtorrent`, such as `--vlc` and `--chromecast`, where is that data stored? Where is the default write location for it?

The torrent is store in the same machine as the webtorrent process and a local server is started to share the files with the media players.

**Comment by raghavprasad13** [comment]
> > When the streaming options are used with `webtorrent`, such as `--vlc` and `--chromecast`, where is that data stored? Where is the default write location for it?
> 
> The torrent is store in the same machine as the webtorrent process and a local server is started to share the files with the media players.

Ah okay. So once I finish streaming the media content I find that I have to restart my computer to get rid of the data downloaded. Is there a more elegant way of doing it?
