### ISSUE TITLE
Busy port detection

### ISSUE THREAD

**Issue by Neo2SHYAlien** [webtorrent/webtorrent-cli#149]
**What version of this package are you using?**
```
webttorrent-cli --version  
3.0.7 (0.108.6)
```

**What operating system, Node.js, and npm version?**
```
Debian Sid
node --version                        
v12.19.0
```

**What happened?**

If I start and the port is used by some other application webtorrent-cli start twice the media player. For example if I use port 8000 (the default streaming port) with `python3 -m http.server` and try to start `webtorrent-cli /link/path --vlc -t /subtitles/path -s 16` VLC is tarted twice. If I close one of the VLC players webttorrent closes immediately, no matters which VLC instance is closed. The very same behavior is observed with mpv/mplayer. I'm aware with port option in cli but still thinks this is a bug.

**Comment by feross** [comment]
Agreed – this sounds like a bug. Anyone want to try fixing it in a PR?

**Comment by feross** [comment]
Agreed – this sounds like a bug. Anyone want to try fixing it in a PR?
