### ISSUE TITLE
File is not downloaded

### ISSUE THREAD

**Issue by aglamazy** [webtorrent/webtorrent-cli#150]
**What version of this package are you using?** 3.2.1

**What operating system, Node.js, and npm version?** Ubuntu 18.04.3 LTS, node v8.10.0, npm 3.5.2

**What happened?**
Seems that file is been downloaded. Showing speed, peers, etc. In the end writes "torrent downloaded successfully from 4/4 peers in 422s!". No file was found :(

**What did you expect to happen?**
Downloaded file in the working directory.

**Are you willing to submit a pull request to fix this bug?** Don't know how.

**Comment by alxhotel** [comment]
Hi @aglamazy,

Thanks for the feedback!

Have you checked your "Downloads", "videos" and temporal folders ?
