### ISSUE TITLE
--announce not working

### ISSUE THREAD

**Issue by aglamazy** [webtorrent/webtorrent-cli#151]
**What version of this package are you using?** 3.2.1 (0.112.1)

**What operating system, Node.js, and npm version?** Ubuntu 18.04.3 LTS, node v8.10.0, npm 3.5.2

**What happened?** I wan't to seed files from a server. Added --annonce <server name> but no traffic goes out to that server.

**What did you expect to happen?** Expected the torrents will be available in webtorrent net. I tested with nast - and no packets were sent to that server.

**Are you willing to submit a pull request to fix this bug?** Don't know.

**Comment by alxhotel** [comment]
Hi @aglamazy,

Thanks for the feedback!

Can you provide us with more info?

What is the exact command you are trying to run?

Maybe the tracker URL you are using is invalid.
