### ISSUE TITLE
Downloads lot of other files when I select single file download using -s option

### ISSUE THREAD

**Issue by askamist** [webtorrent/webtorrent-cli#153]
**What version of this package are you using?**
3.2.1

**What operating system, Node.js, and npm version?**
Linux, v12.16.3, 1.22.10 (yarn)

**What happened?**
`webtorrent` package uses `torrent.so.includes` method to select the files to download, and I think it expects `torrent.so` to be array of indexes to downloads, but it is set to `argv.select.toString()` in the code. it is not breaking since the string also has a `includes` method, but is selecting a lot of other files to download for example If I pass `1378` to `-s` options, it would download 1,13,37...etc, since `"1378".includes(13)` returns true.  

**What did you expect to happen?**
download just the selected file (with `-s`).

**Are you willing to submit a pull request to fix this bug?**
Yes.

**Comment by obrie** [comment]
For what it's worth, I'm experiencing the same issue.

**Comment by OsmanAltun** [comment]
This half fixes it
```typescript
// array lookin like this: [593, 10] when -s 593,10
torrent.so = argv.select.toString().split(',').map(v => {
        try {
          return parseInt(v)
        } catch (err) {
          errorAndExit(err)
        }
      })
```
But it still takes one index above and one below, which is maybe a webtorrent bug?
if I were to do -s 10 it will download files 9, 10, 11
