### ISSUE TITLE
Intermittent crash when attempting download using magnet link on startup

### ISSUE THREAD

**Issue by mikedeboer** [webtorrent/webtorrent-cli#170]
**What version of this package are you using?**

webtorrent-cli 3.3.0, webtorrent 1.0.2

**What operating system, Node.js, and npm version?**

Mac OSX 11.3.1 (Intel), node v14.17.1, npm 7.19.0

**What happened?**

Hit `webtorrent download "magnet:..."` from the command line (iTerm2, ZSH), saw that Webtorrent found the tracker, got a list of peers and cleared the screen into interactive mode. I susoect it failed to connect to one of the peers.

Full error:

```
DEBUG INFO: webtorrent-cli 3.3.0, webtorrent 1.0.2, node v14.17.1, darwin x64, exit 1
/Users/mikedeboer/.nvm/versions/node/v14.17.1/lib/node_modules/webtorrent-cli/node_modules/utp-native/lib/connection.js:197
  binding.utp_napi_connect(this._utp._handle, this._handle, port, ip)
          ^

Error: invalid argument
    at Connection._connect (~/.nvm/versions/node/v14.17.1/lib/node_modules/webtorrent-cli/node_modules/utp-native/lib/connection.js:197:11)
    at ~/.nvm/versions/node/v14.17.1/lib/node_modules/webtorrent-cli/node_modules/utp-native/lib/connection.js:189:10
    at processTicksAndRejections (internal/process/task_queues.js:83:21) {
  code: 'EINVAL'
}
```

The error is caused by the `utp-native` module, which may require a fix and/ or update.

Please feel free to reach out to me directly for an example magnet link!

**What did you expect to happen?**

Gracefully handle the error and recover - if a peer connect failure was at fault, I expect Webtorrent to disqualify it and move on to the next.

**Are you willing to submit a pull request to fix this bug?**

Perhaps - but finding the time might be difficult.

**Comment by mikedeboer** [comment]
After a little investigation and fiddling, I ended up at https://github.com/mafintosh/utp-native/compare/master...mikedeboer:connect_may_throw?expand=1 to make it work nicely for me.
I think getting this integrated upstream might require introducing a 'quiet' mode switch, or something, but it's a start!

**Comment by mikedeboer** [comment]
Alright, trying some more... doesn't seem to fix it unless I completely comment `binding.utp_napi_connection_close(this._handle)` out, which is not really an option... but perhaps a 'noClose' mode works for webtorrent?

**Comment by ThaUnknown** [comment]
utp-native only supports IPv4, when connecting to IPv6 peers it crashes, see: https://github.com/webtorrent/webtorrent/issues/2114
you're best off disabling utp until this is fixed

**Comment by IdanAdar** [comment]
How to disable?

**Comment by IdanAdar** [comment]
Looks like a fix is ready for picking?

**Comment by DiegoRBaquero** [comment]
Should be fixed in last version :)

**Comment by IdanAdar** [comment]
@DiegoRBaquero There is a newer version than 3.3.0?

**Comment by DiegoRBaquero** [comment]
Reinstall should use latest webtorrent, where the fix happened 

Diego
