### ISSUE TITLE
webtorrent --mpv order changed in 3.3?

### ISSUE THREAD

**Issue by leshow** [webtorrent/webtorrent-cli#178]
**What version of this package are you using?**
3.4.0

**What operating system, Node.js, and npm version?**
linux 5.12 - arch - node 16.5 - npm 7.17

**What happened?**
The order of the arguments for `--mpv` or `--vlc` appears to have changed, breaking my old aliases. You used to be able to write: 
```
webtorrent --mpv "magnet: ... "
```
Now it looks like it must be:
```
webtorrent "magnet: ... " --mpv
```

**What did you expect to happen?**
expected both arg orders to work, if the method I've been using was supported changing it would be a breaking change

**Are you willing to submit a pull request to fix this bug?**
Absolutely, if you'll accept it? If the way I've been using only ever worked accidentally feel free to close this issue.

**Comment by DiegoRBaquero** [comment]
Both should work, yeah. Happy to review PR

Diego
