### ISSUE TITLE
Show files in webtorrent info

### ISSUE THREAD

**Issue by noctuid** [webtorrent/webtorrent-cli#186]
**What version of this package are you using?**
3.5.3

**What problem do you want to solve?**
I maintain an mpv script for direct integration with mpv (various advantages over --mpv) and would like to be able to simply get a list of urls that webtorrent creates. Currently, in order to do this I have to parse the html of `localhost:<port>` which isn't ideal.

**What do you think is the correct solution to this problem?**
I previously suggested #132. As an alternative, it would be nice if `webtorrent info` provided a list of files inside the torrent. I could then concatenate `localhost:<port>/<#>/` to the filenames to get the urls. I think this would be useful besides for my limited use case.

Other commandline tools can do this for a torrent file, but I'm not aware of any that can format the file list for scripts (e.g. in json), and I'd rather only have webtorrent-cli as a dependency of the script. This is not a huge deal, but I think it would be a nice improvement

**Are you willing to submit a pull request to implement this change?**
I don't have the time/knowledge.

**Comment by pc00per** [comment]
How to list files? I'm confused. I don't get filelist information on `webtorrent info`
