### ISSUE TITLE
How to change the default output location? 

### ISSUE THREAD

**Issue by ttx99** [webtorrent/webtorrent-cli#205]
how to permanently change the default output location for streaming? I wanna change it to video or download folder in linux.

**Comment by ttx99** [comment]
I mean is  there like a config file I can edit to make some settings permanent?

**Comment by jbardi** [comment]
> how to permanently change the default output location for streaming? I wanna change it to video or download folder in linux.

Why not just make an alias in .bashrc or write a bash script for each of the paths you want to save to.

So you can have one called webtorrent-video or webtorrent-downloads

alias webtorrent-downloads="webtorrent -o /home/myaccount/downloads"

or bash script called webtorrent-downloads located in your $PATH
```
#!/bin/bash

webtorrent -o /home/myaccount/downloads $1
```

Then just enter webtorrent-downloads [torrent-file or magnet link] at the terminal
