### ISSUE TITLE
Option to stream using Celluloid

### ISSUE THREAD

**Issue by quasigod-io** [webtorrent/webtorrent-cli#206]
**What version of this package are you using?**
webtorrent-cli 4.0.0-1

**What problem do you want to solve?**
I use Celluloid and from my experience talking to other Linux users it's a very commonly used player.

**What do you think is the correct solution to this problem?**
I think --celluloid should be added as an option.

**Are you willing to submit a pull request to implement this change?**
I don't know any Javascript unfortunately. Although if this never get's added I'll add it once I've learned some.

**Comment by ThaUnknown** [comment]
Celluloid is mpv based, so it should be supported already?

**Comment by quasigod-io** [comment]
It is MPV based but I don't believe there is a way to watch a stream through it using webtorrent. With Celluloid installed --mpv will still run it in stock mpv.
