### ISSUE TITLE
Syntax Error -Can't Access webtorrent with command "webtorrent"

### ISSUE THREAD

**Issue by whitedevil-glitch** [webtorrent/webtorrent-cli#212]
**What version of this package are you using?**
latest
**What operating system, Node.js, and npm version?**
Zorin OS 16 and 6.14.4
**What happened?**
whenever i try to run the "webtorrent" command it shows syntax error -- unexpected identifier
**What did you expect to happen?**
i expected to show the commands of webtorrent which I can run through CLI
**Are you willing to submit a pull request to fix this bug?**
If it's necessery, yes.

Issue:-
![image](https://user-images.githubusercontent.com/73755149/148016504-a37d33be-0c1b-4997-8347-69ce21a17d3e.png)

**Comment by alxhotel** [comment]
Hi @whitedevil-glitch,

You need at least Node 12.20

**Comment by whitedevil-glitch** [comment]
Ok thank you @alxhotel
