### ISSUE TITLE
webtorrent not installind due to permission denied

### ISSUE THREAD

**Issue by aj-arts** [webtorrent/webtorrent-cli#214]
![image](https://user-images.githubusercontent.com/95337072/148098864-4205f35c-977d-41f5-9b3b-854f9c58784b.png)

**Comment by DiegoRBaquero** [comment]
This is not an issue with webtorrent-cli. npm doesn't have access to `/usr/local/lib`. Try running with `sudo`

**Comment by aj-arts** [comment]
doesnt work gives public key error

**Comment by DiegoRBaquero** [comment]
Please share the log

**Comment by aj-arts** [comment]
npm install webtorrent-cli -g give me the above error and this the log file

[2022-01-04T18_00_43_169Z-debug.log](https://github.com/webtorrent/webtorrent-cli/files/7809492/2022-01-04T18_00_43_169Z-debug.log)

**Comment by DiegoRBaquero** [comment]
I don't see the public key error. All I see is `EACCES: permission denied, mkdir '/usr/local/lib/node_modules'`, but that's not an issue with webtorrent-cli

**Comment by aj-arts** [comment]
sudo npm install webtorrent-cli -g

![image](https://user-images.githubusercontent.com/95337072/148106243-17581595-413c-445a-8d87-d78cfd312253.png)

**Comment by DiegoRBaquero** [comment]
Ah, this should have fixed it: https://github.com/webtorrent/webtorrent-cli/commit/8e4c77f791e5811f56284adc74ff6fc0666b2149

🤔 

Try stating the version `sudo npm install -g webtorrent-cli@4.0.2`

**Comment by aj-arts** [comment]
![image](https://user-images.githubusercontent.com/95337072/148106860-95bdc52d-442d-49c3-8528-647e5b54f7c8.png)
still error

**Comment by DiegoRBaquero** [comment]
Ugh, I'm sorry this is happening. I'll look into this later

**Comment by aj-arts** [comment]
ok btw thnx @DiegoRBaquero for considering to help a noob like me this inspires me to become a foss dev ...helping people etc

**Comment by mishailovic** [comment]
> Ugh, I'm sorry this is happening. I'll look into this later

Btw, didn't want to create another issue, but it would be nice to pack the app with https://github.com/leafac/caxa or something like that.
