### ISSUE TITLE
How do I change the output directory when streaming?

### ISSUE THREAD

**Issue by ahuactl** [webtorrent/webtorrent-cli#220]
When streaming large files, my `/tmp` folder fills up quickly. Is there a way to change the output directory when streaming?

**Comment by stl3** [comment]
I would also like to know if there is any way to specify output dir when streaming - I have a very limited /tmp file size on my Raspberry Pi 4B so streaming stuff at a higher quality is limited a certain size. I have plenty of space outside of /tmp though. Any way to go about doing this?

**Comment by ahuactl** [comment]
It worked for me, thanks!
