### ISSUE TITLE
Display multiple torrents

### ISSUE THREAD

**Issue by br3ndonland** [webtorrent/webtorrent-cli#224]
**What version of this package are you using?** 4.0.3

**What problem do you want to solve?** Display info about multiple torrents

**What do you think is the correct solution to this problem?** Display each torrent being downloaded or seeded

**Are you willing to submit a pull request to implement this change?** Yeah, could totally take a stab at it

## Description

Thanks for WebTorrent! :sparkling_heart:

webtorrent-cli can download multiple torrents by passing multiple filepaths or magnet links as arguments, like `webtorrent download *.torrent`. This multi-torrent support is helpful.

When more than one torrent is specified, webtorrent-cli automatically enables quiet mode (equivalent to the `--quiet` flag):

https://github.com/webtorrent/webtorrent-cli/blob/bbbe6ef6bdb033178c2615e3d36703a3afd970f7/bin/cmd.js#L831-L839

This means the user is unable to see the status of any of the torrents.

## Suggestions

It would be great to have a compact display of each torrent being downloaded or seeded.

I would propose something like this:

- Display each torrent in 1-2 lines, with select metadata:
  - name
  - download speed and size
  - upload speed and size
  - peers
- When the number of torrents exceeds the height of the terminal window, abbreviate the list like `... and <n> more` (the current behavior for displaying peers)

It might look like [this](https://carbon.now.sh/?bg=rgba%28171%2C+184%2C+195%2C+1%29&t=dracula-pro&wt=none&l=text&width=480&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=29px&ph=31px&ln=false&fl=1&fm=dm&fs=15px&lh=133%25&si=false&es=1x&wm=false&code=%252Fpath%252Fto%252Fmy%252Ftorrents%250A%25E2%259D%25AF%2520webtorrent%2520download%2520*.torrent%250A%250A%2520%2520pwned-passwords-sha1-ordered-by-count-v8.7z%250A%2520%2520Download%253A%252019%2520GB%252F19%2520GB%2520%28N%252FA%29%2520%2520%2520%2520%2520%2520%2520%2520Upload%253A%25206.1%2520MB%2520%281.2%2520MB%252Fs%29%2520%2520%2520%2520%2520Peers%253A%25201%252F1%250A%250A%2520%2520origin_species_librivox%250A%2520%2520Download%253A%25202.4%252F4.0%2520GB%2520%2828%2520KB%252Fs%29%2520%2520%2520%2520%2520Upload%253A%2520240%2520KB%2520%28100%2520KB%252Fs%29%2520%2520%2520%2520%2520Peers%253A%25202%252F3%250A%250A%2520%2520Sintel%250A%2520%2520Download%253A%2520100%252F129%2520MB%2520%2818%2520MB%252Fs%29%2520%2520%2520%2520%2520Upload%253A%2520249%2520KB%2520%28120%2520KB%252Fs%29%2520%2520%2520%2520%2520Peers%253A%252012%252F12%250A%250A%2520%2520...%2520and%252010%2520more):

<img src="https://user-images.githubusercontent.com/26674818/152658037-3027eec0-2653-471a-b916-71c1dc1b9ea0.png" alt="Example of webtorrent-cli multi-torrent display in a terminal, made with carbon.now.sh" width="800px" height="" />

It's probably a good idea to support the `--quiet` flag, in case users want to preserve the existing behavior.

## Related

- webtorrent/webtorrent-cli#20
- webtorrent/webtorrent-cli#21
- webtorrent/webtorrent-cli#81
- webtorrent/webtorrent-cli#177

Torrents from screenshot:

- [Pwned passwords list](https://haveibeenpwned.com/Passwords) (Have I Been Pwned - help Troy Hunt [reduce egress fees](https://www.troyhunt.com/how-i-got-pwned-by-my-cloud-costs/))
- [The Origin of Species by Charles Darwin](https://librivox.org/the-origin-of-species-by-charles-darwin/) (LibriVox)
- [Sintel](https://webtorrent.io/docs) (WebTorrent)

**Comment by DiegoRBaquero** [comment]
This would be great! happy to review a PR :)

**Comment by br3ndonland** [comment]
yes #240

**Comment by br3ndonland** [comment]
yes #240

**Comment by br3ndonland** [comment]
yes #240
