### ISSUE TITLE
Internet disconnectivity while streaming

### ISSUE THREAD

**Issue by pc00per** [webtorrent/webtorrent-cli#228]
**What version of this package are you using?**
webtorrent-cli 4.0.3, webtorrent 1.8.1

**What operating system, Node.js, and npm version?**
node v17.3.1, Linux arch 5.16.9-arch1-1

**What happened?**
The ethernet connection fluctuates while streaming. So web surfing gets interrupted when a stream is running.

**What did you expect to happen?**
Streaming should run fine without any internet disconnectivity. 

**Are you willing to submit a pull request to fix this bug?**
No.

**Comment by DiegoRBaquero** [comment]
Is the video already fully downloaded when internet connection is lost?

**Comment by pc00per** [comment]
> Is the video already fully downloaded when internet connection is lost?

No. It happens inbetween.

**Comment by pc00per** [comment]
Donno. It's still happening.
Websites stop loading while MPV instance running in the background.
I have to refresh the website continuously & it'll load up randomly.

**Comment by pc00per** [comment]
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?

I donno. I'm not using it recently & I might just download & watch later the traditional way (even though it negatives the main principle of webtorrent). Or just buy https://webtor.io subscription as an another alternative (caz they even support streaming without downloading too).
As no one experienced this, I will close it. If you believe others might encounter the same, feel free to open this again.
