### ISSUE TITLE
--select just downloads all files in torrent rather than the specified one

### ISSUE THREAD

**Issue by StavrosHacker** [webtorrent/webtorrent-cli#248]
**What version of this package are you using?**
4.1.0 (1.8.24)

**What operating system, Node.js, and npm version?**
CentOS 7, v14.17.1, 6.14.3

**What happened?**
When I use the --select option followed by the number of the file I want to be downloaded, webtorrent just goes ahead and downloads all the files, rather than only the file I specified.

**What did you expect to happen?**
For only the specified file to be downloaded and after the file downloads, for the program to exit.

**Are you willing to submit a pull request to fix this bug?**
Not at the moment, as I do not have the time to dig through the code.

**Comment by ThaUnknown** [comment]
fixed in 5.0.1 #304
