### ISSUE TITLE
Download only file that's being requested

### ISSUE THREAD

**Issue by iodream** [webtorrent/webtorrent-cli#250]
**What version of this package are you using?**
4.1.0 (1.8.29)

**What problem do you want to solve?**
Currently Webtorrent by default downloads all files when given a magnet url or torrent file. Scripts like [mpv-webtorrent-hook](https://github.com/noctuid/mpv-webtorrent-hook) rely on starting up Webtorrent, adding all the urls from Webtorrent into a playlist and then start streaming the files selected. 

Often there is the use case where you want to stream/access one individual file and have no immediate use for the others for this session, however Webtorrent is still up and downloading/seeding everything else in the background, wasting IO and bandwidth, especially if the user has it set to remove the files downloaded on exit.

**What do you think is the correct solution to this problem?**
Could Webtorrent perhaps have a flag (for those scripts to use) to detect those files being requested right now and download only those(and perhaps optionally the X neighboring files too for caching interests)?

**Are you willing to submit a pull request to implement this change?**
I can't submit a PR for lack of JS knowledge

**Comment by pc00per** [comment]
Yes. Absolutely. I've always try to listen just one song from a torrent album. And it always downloads the entire album songs. The same happens with web series too. Just wanna watch a single episode, but it literally downloads the whole season for some odd reason. Just a waste of bandwidth.
I think `-s` is broken.

**Comment by pc00per** [comment]
Yay. This issue is fixed as GitHub bot said (sarcasm)
....¯\\\_(ツ)_/¯
