### ISSUE TITLE
bash-completion support for options

### ISSUE THREAD

**Issue by ghost** [webtorrent/webtorrent-cli#251]
**What version of this package are you using?**
4.1.0 (1.8.29)

**What problem do you want to solve?**
[bash-completion](https://github.com/scop/bash-completion) for webtorrent-cli options

**What do you think is the correct solution to this problem?**
provide tab completions ?

**Are you willing to submit a pull request to implement this change?**
NA

**Comment by pc00per** [comment]
I'm not sure I can reply to a bot.
