### ISSUE TITLE
multiple magnet download

### ISSUE THREAD

**Issue by edenlith** [webtorrent/webtorrent-cli#302]
**What version of this package are you using?**

**What problem do you want to solve?**

**What do you think is the correct solution to this problem?**

**Are you willing to submit a pull request to implement this change?**

Greetings. I was wondering if it is possible to add a feature to download multiple magnets at the same time using the command line.

Thanks.

**Comment by johnpaulensign** [comment]
Here is an example of the command, running on macOS:

```bash
echo "ubuntu.iso.torrent raspios.img.torrent linuxmint.iso.torrent" | xargs -n 1 -P 0 webtorrent download -o ../
```

I don't know that this will work on Linux's xargs.

**Comment by edenlith** [comment]
> Here is an example of the command, running on macOS:
> 
> ```shell
> echo "ubuntu.iso.torrent raspios.img.torrent linuxmint.iso.torrent" | xargs -n 1 -P 0 webtorrent download -o ../
> ```
> 
> I don't know that this will work on Linux's xargs.

Thanks for the reply. I'm using Windows 11 so I created a dos script to solve this problem.
