### ISSUE TITLE
Installing 5.1.1 results in an error

### ISSUE THREAD

**Issue by smhmd** [webtorrent/webtorrent-cli#312]
**What version of this package are you using?**
5.1.1
**What operating system, Node.js, and npm version?**
MacOS (and Windows 8.1) Node 20, 21, and 22 and NPM 10
**What happened?**
Installed webtorrent globally and I get the following (downgrading to 5.1.0 fixes the issue)

<img width="800" alt="image" src="https://github.com/webtorrent/webtorrent-cli/assets/46059092/ae688540-55e7-4359-a3ab-95835a29e686">

**What did you expect to happen?**
To not see the error

**Are you willing to submit a pull request to fix this bug?**
Not sure, if you want me to look into it, let me know

**Comment by SilentBot1** [comment]
Yep, sorry, this is my bad, a mistake was released as of 5.1.1 in PR #309.

The PR to fix this is already open here: https://github.com/webtorrent/webtorrent-cli/pull/311 I'm currently waiting for a review, but this will likely not occur for ~12 hours.

You can use `npx webtorrent-cli@5.1.0` or pin `webtorrent-cli@5.1.0` until the PR above is released.
