### ISSUE TITLE
(Documentation request) Document how to run the program with npm

### ISSUE THREAD

**Issue by hardBSDk** [webtorrent/webtorrent-cli#317]
It explain how to install the program from the npm servers but not how to run it from this repository.

**Comment by SilentBot1** [comment]
Hey @hardBSDk,

Can you clarify what you are requesting in the above?

Do you mean running this via npx, e..g `npx webtorrent-cli --help`, or do you mean after cloning the git repository locally via `node ./bin/cmd.js --help`?

**Comment by hardBSDk** [comment]
@SilentBot1 `npm run`

**Comment by SilentBot1** [comment]
@hardBSDk hey

The `npm run` command (an alias of `npm run-script`) is for running `scripts` from a `package.json` as documented [here](https://docs.npmjs.com/cli/v10/commands/npm-run-script).

`webtorrent-cli` does not have a `npm run` command for invoking the CLI, the only supported ways to run the CLI are the already documented ways:
- `npx webtorrent-cli --help`
- `npm i -g webtorrent-cli` and then `webtorrent-cli --help`
