### ISSUE TITLE
Magnet link doesn't work

### ISSUE THREAD

**Issue by ttx99** [webtorrent/webtorrent-cli#318]
![1](https://github.com/user-attachments/assets/8b519306-78c0-4263-ae59-aa4a5dbf2504)
 it stays like this 
![2](https://github.com/user-attachments/assets/cb8e58a2-517d-47f1-9c23-8a8ad249ad68)

**Comment by ttx99** [comment]
for context that magnet link is for deadpool vs wolverine so seeds should not be an issue at the time I posted.

**Comment by edenlith** [comment]
same problem

**Comment by SilentBot1** [comment]
Hi @ttx99,

We do not endorse piracy, please replace your examples with non-copywritten content.

If you wrap the wrap with speech marks `"`, does this help the situation?

Can you try to use `npx webtorrent` instead of just `webtorrent` to ensure you're using the latest version?

If neither of the above works, can you run the command `DEBUG=* npx webtorrent ...` with a test file and share the logs it generates?

**Comment by ttx99** [comment]
How do i get the logs?

**Comment by ttx99** [comment]
I mean where are the logs located?

**Comment by SilentBot1** [comment]
You enable logs by setting the environment variable DEBUG to *, e.g. `DEBUG=* webtorrent`, `DEBUG=* npx webtorrent-cli`, etc.

**Comment by ttx99** [comment]
where is the log file saved after I run than command?

**Comment by SilentBot1** [comment]
@ttx99 the log entries are output to stdout, so your console, so you'd either need to redirect/tee, or grab them from however you're running your service/process.

**Comment by ttx99** [comment]
@SilentBot1 Sorry I dont know how to do that.

**Comment by SilentBot1** [comment]
@ttx99 what operating system are you on?

For Windows, run the command: 

```
npx webtorrent-cli@5.1.2 download "your-magnet-here" > log.log 2>&1
```

**Comment by ttx99** [comment]
Manjaro linux

**Comment by ttx99** [comment]
Linux
[webttorent.log](https://github.com/user-attachments/files/16757611/webttorent.log)

**Comment by ttx99** [comment]
linux

DEBUG=*npx@5.1.2 webtorrent -o ~/Downloads/ --mpv --not-on-top "magnet" | tee webtorrent.log

here
[webtorrent.log](https://github.com/user-attachments/files/16757851/webtorrent.log)

**Comment by SilentBot1** [comment]
Hey @ttx99, 

This only included part of the logs, you will also need to include stderr by doing:
```bash
DEBUG=* npx@5.1.2 webtorrent -o ~/Downloads/ --mpv --not-on-top "magnet" 2>&1 | tee webtorrent.log
```
or 
```bash
DEBUG=* npx@5.1.2 webtorrent -o ~/Downloads/ --mpv --not-on-top "magnet" |& tee webtorrent.log
```

**Comment by ttx99** [comment]
DEBUG=* npx@5.1.2 webtorrent -o ~/Downloads/ --mpv --not-on-top "magnet" |& tee webtorrent.log

here:
[webtorrent.log](https://github.com/user-attachments/files/16781054/webtorrent.log)
