### ISSUE TITLE
Downloading from infohashes no longer appears to work.

### ISSUE THREAD

**Issue by ZachB-AUT** [webtorrent/webtorrent-cli#319]
**What version of this package are you using?**
4.1.0 (1.8.22)

**What operating system, Node.js, and npm version?**
OS: MacOS 12.0.1
**What happened?**
Running the command:
```
webtorrent [INSERT INFOHASH]
```
Brings up
```
fetching torrent metadata from 0 peers
```
And stays this way indefinitely.

**What did you expect to happen?**
Previously this would then proceed to download the torrent associated with that infohash

**Are you willing to submit a pull request to fix this bug?**
I do not know how.

## Additional information:
This appears to be related to an upstream issue with the webtorrent library:
[As reported in this issue](https://github.com/webtorrent/webtorrent/issues/2850)

Downloading from magnet links still works, but is much less convenient for me than downloading from infohashes.

**Comment by ZachB-AUT** [comment]
Additionally, using
```
npx webtorrent [infohash] 
```
does not work either.

**Comment by k7ragav** [comment]
Yeah I have the same issue as above

**Comment by iWedmak** [comment]
same, trying to debug it in discord

**Comment by koynpurse** [comment]
I'm having the same issue.
