### ISSUE TITLE
Detect subtitle files and pass them automatically to supported players

### ISSUE THREAD

**Issue by CyberShadow** [webtorrent/webtorrent-cli#34]
If the torrent file contains any .sub or .srt files, it would be neat to pass them to players, e.g. via `mpv`'s `--sub-file` option (which accepts URLs just as well as for the main video file).

**Comment by iovis9** [comment]
What if there are more than one? I just saw mpv can be called with multiple `--sub-file` intances, but VLC appears to only support one, for instance.

**Comment by CyberShadow** [comment]
Hmm, well, let's look at the possible reasons why there could be multiple subtitle files in one torrent:

- The torrent contains multiple video files and accompanying subtitle files, e.g. if it contains an entire season of some TV show. In this case the user is expected to manually pick the video file they desire to watch anyway.
- There are subtitles for multiple languages. I don't think we can reasonably pick the 'correct' one for the user here; ideally, the player would support reading multiple subtitle files and then use the same preference it uses to select among embedded subtitles.
- There are multiple formats of the same subtitles. I guess we can have a preference order of file extensions (e.g. `ass` > `srt` > `sub` > `vob`) OSLT.

Generally, considering that the most common player that's used together with webtorrent-cli supports multiple torrent files, I don't think it's worth spending much time thinking about this.

**Comment by CyberShadow** [comment]
> If so, what is blocking it?

Someone implementing it.

**Comment by CyberShadow** [comment]
> If so, what is blocking it?

Someone implementing it.

**Comment by CyberShadow** [comment]
I believe this has been wrongly closed.

**Comment by DiegoRBaquero** [comment]
If there's no one willing to implement it for now, it should remain closed.

**Comment by ThaUnknown** [comment]
I have implemented something like this, detecting subtitle files for the currently playing file is simple, but actually passing them to the player is black magic for me, you can find the JS for detecting sub files here:
https://github.com/ThaUnknown/webtorrent-player/blob/main/index.js#L1109-L1145

**Comment by CyberShadow** [comment]
> If there's no one willing to implement it for now, it should remain closed.

What is the logic by which issues should be open or closed? And, how would one distinguish actionable and non-actionable issues if both kinds are closed?

It would be helpful if there was a document in the repository describing the processes involved. That would also be helpful to avoid setting wrong expectations for future contributors.

> but actually passing them to the player is black magic for me

Is this something that could be discussed / collaborated on to figure out a solution?
