### ISSUE TITLE
How create and seed own torrent throught own webtorrent-tracker? Step by step.

### ISSUE THREAD

**Issue by dxpsite** [webtorrent/webtorrent-cli#35]
Begin want download some exist file such from tracker.btorrent.xyz for example - https://webseed.btorrent.xyz/timedrift-alpine-4k-timelapse.mp4

but it can't:
http://clip2net.com/clip/m455449/38c52-clip-12kb.png

Create webtorrent-tracker with default port.. its work good.. stats show zero..

ok.. I'm trying to create a torrent myself with command like:
`webtorrent create /usr/src/mvs/test.mp4.torrent --announce http://somedomain`
okay, got that: 
```
root@dxp: usr/src/mvs# webtorrent create /usr/src/mvs/test.mp4.torrent --announce http://somedomain
d8:announce16:http://somedomain13:announce-listll16:http://somedomainee10:created by34:WebTorrent https://webtorrent.io13:creation datei1494531671e8:encoding5:UTF-84:infod6:lengthi10521e4:name16:test.mp4.torrent12:piece lengthi16384e6:pieces20:▒F▒▒4TԖ M(h▒
```

How can I make everything work so that the torrent through the preview is visible at http://somedomain/stats and could I further specify on a separate page to show visitors?
What am I doing wrong?

p.s. webseed work correctly use this manual: https://hackernoon.com/how-to-create-a-swarm-cdn-for-free-with-webtorrent-bfa09d193f71
but own torrents..

**Comment by DiegoRBaquero** [comment]
1. You can't download an http(s) file with webtorrent. If you'd like to do that use curl or wget.
2. Following the blog post, just use your own files, you must create the torrent file and expose it on an http server, same goes for the webseeded file.
