### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by iovis9** [webtorrent/webtorrent-cli#44]
It's been a while since we release a new version and there's been some meaningful changes since our latest one.

**Comment by Ciao121** [comment]
What is the question?

**Comment by iovis9** [comment]
As it says in the CONTRIBUTING.md:
> Declaring formal releases remains the prerogative of the project maintainer.

So I'm asking the maintainer, @feross, if we should do a new release with the latest changes.

**Comment by DiegoRBaquero** [comment]
v1.11.0 released :)
