### ISSUE TITLE
on-done script not executing and process hangs

### ISSUE THREAD

**Issue by Alanz2223** [webtorrent/webtorrent-cli#45]
Hello guys, I have several magnet links I want to download at once so and in order to have them download in the background I've decided to run the webtorrent-cli command as a pm2 job. I have a simple shell script with the following `webtorrent download $1 --on-done ../scripts/downloadFinished.js` where download finished is basically this 

`var execSync = require("child-process").execSync;
var cmd = "curl " + options;

var stdout = execSync(cmd);

console.log(stdout);`

The problem is that I am not seeing any output from the script and most importantly the script seems to not be executing at all since the curl request isn't going through while it executes just fine on its own. The other thing is that the torrent will download fine but the webtorrent job hangs with the message
`webtorrent is exiting...` but it never actually exits and that happens whether or not I pass it the on-done option. I've also tried passing a shell script that executes node passing it the actual script to execute, and that doesnt work either.

`webtorrent --version : 1.10.1 (0.98.19)`

**Comment by Alanz2223** [comment]
Ok I've done a bit more troubleshooting. I thought that the contents of the actual script were what was causing it not execute but I created a dummy file and had it simply write to a file 

`var fs = require("fs"); \

fs.writeFileSync("./test.txt", "file written succesfully");`

but even that doesn't work. Also I tried using the --on-exit option instead of on-done and I still have similar results.

**Comment by DiegoRBaquero** [comment]
Try `webtorrent download $1 --on-done "node ../scripts/downloadFinished.js"`
