### ISSUE TITLE
Can don't download files through magnet link

### ISSUE THREAD

**Issue by code-moritz** [webtorrent/webtorrent-cli#46]
The new webtorrent-cli version can't download files through magnet link. 

The terminal show can't connect peer node. 

`fetching torrent metadata from 0 peers`

but the webtorrent-desktop app work fine.  I guess the new version has some issues. 

system info:
OS: Mac OS 10.13  

and how to uninstall webtorrent-cli on mac?

**Comment by iovis9** [comment]
I just tried the last version (1.11) without issues. Did you pass the magnet link surrounded by double quotes?
```sh
webtorrent download "magnet:?xt=urn:..."
```

If you want to uninstall webtorrent-cli I'm guessing this should be enough:
```sh
npm -g uninstall webtorrent-cli
```

**Comment by DiegoRBaquero** [comment]
Beware that webtorrent-cli alone can only connect to TPC/UDP peers, while Desktop App can also connecto to WebRTC peers. Did you try other magnets?

**Comment by code-moritz** [comment]
@iovis9  Thank you very much. according your suggest, my problem was solved . maybe the latest version change the command format. so. i use the old download command , and can't download the files. 

thank you. @iovis9 @DiegoRBaquero

**Comment by feross** [comment]
@code-moritz Maybe your terminal changed? I believe that zsh requires quotes around the magnet link, while bash does not.
