### ISSUE TITLE
Cant stream to Chromecast

### ISSUE THREAD

**Issue by Lobotuerk** [webtorrent/webtorrent-cli#49]
When i try to stream to chromecast, i get: getaddrinfo ENOTFOUND e98e8263-c4ea-48f4-3c10-873dce91fc3e.local e98e8263-48f4-3c10-873dce91fc3e.local:8009, any solution? Streaming from the desktop version works fine, but im working on a node app and I need the cli version

**Comment by benoitparis** [comment]
Same for me. Not using vpn.

**Comment by Lobotuerk** [comment]
No vnp used

**Comment by iovis9** [comment]
I don't have a Chromecast to test with :(
So I have no idea if this is an issue with this package or our dependency (see https://github.com/mafintosh/chromecasts) or your env.

**Comment by kim0** [comment]
Check the `--my-ip` parameter and set it to the IP of your laptop :/

**Comment by feross** [comment]
Which version of Chromecast is not working? Can someone share the hardware model and software version?

**Comment by lidel** [comment]
@feross I got the same `Error: Chromecast: getaddrinfo ENOTFOUND`  with latest `webtorrent-cli` on a workstation with multiple network interfaces (ipv4+6 eth0, dockerN, etc) 

Chromecast 2, Cast firmware version: 1.32.124602

Is there anything I can pass to get more debug info for you?

**Comment by DiegoRBaquero** [comment]
Very old issue, closing. Feel free to re-open
