### ISSUE TITLE
UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!     

### ISSUE THREAD

**Issue by yuehan** [webtorrent/webtorrent-cli#50]
webtorrent is exiting...                                                             
Select a file to download:                                                           
                                                                                     
To select a specific file, re-run `webtorrent` with "--select [index]"               
Example: webtorrent download "magnet:..." --select 0                                 
                                                                                     
webtorrent is exiting...                                                             
                                                                                     
UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!                         
OPEN AN ISSUE: https://github.com/webtorrent/webtorrent-cli/issues                   
                                                                                     
DEBUG INFO: webtorrent-cli 1.11.0, webtorrent 0.98.20, node v9.2.1, win32 ia32, exit 
1                                                                                    
D:\apps\node-v9.2.1-win-x86\node_modules\webtorrent-cli\node_modules\webtorrent\index
.js:407                                                                              
  if (this.destroyed) throw new Error('client already destroyed')                    
                      ^                                                              
                                                                                     
Error: client already destroyed                                                      
    at WebTorrent.destroy (D:\apps\node-v9.2.1-win-x86\node_modules\webtorrent-cli\no
de_modules\webtorrent\index.js:407:29)                                               
    at gracefulExit (D:\apps\node-v9.2.1-win-x86\node_modules\webtorrent-cli\bin\cmd.
js:703:10)                                                                           
    at Torrent.onReady (D:\apps\node-v9.2.1-win-x86\node_modules\webtorrent-cli\bin\c
md.js:417:14)                                                                        
    at Object.onceWrapper (events.js:254:19)                                         
    at Torrent.emit (events.js:164:20)                                               
    at Torrent._onStore (D:\apps\node-v9.2.1-win-x86\node_modules\webtorrent-cli\node
_modules\webtorrent\lib\torrent.js:631:8)                                            
    at D:\apps\node-v9.2.1-win-x86\node_modules\webtorrent-cli\node_modules\webtorren
t\lib\torrent.js:612:10                                                              
    at end (D:\apps\node-v9.2.1-win-x86\node_modules\webtorrent-cli\node_modules\run-
parallel-limit\index.js:17:15)                                                       
    at done (D:\apps\node-v9.2.1-win-x86\node_modules\webtorrent-cli\node_modules\run
-parallel-limit\index.js:21:10)                                                      
    at each (D:\apps\node-v9.2.1-win-x86\node_modules\webtorrent-cli\node_modules\run
-parallel-limit\index.js:28:7)

**Comment by DiegoRBaquero** [comment]
What was the command you run?

**Comment by feross** [comment]
It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.
