### ISSUE TITLE
UNEXPECTED ERROR

### ISSUE THREAD

**Issue by ImAWizardLizard** [webtorrent/webtorrent-cli#53]
Attempting to open a file using --chromecast or --vlc so far generates this error.

Error: not a number: buffer[0] = 26

UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/webtorrent/webtorrent-cli/issues

DEBUG INFO: webtorrent-cli 1.11.0, webtorrent 0.98.20, node v9.3.0, linux x64, exit 1

**Comment by rom1504** [comment]
What file ?

**Comment by feross** [comment]
It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.

**Comment by mstred** [comment]
Reproduced here while trying to use on macOS:

```bash
$ webtorrent download http://releases.ubuntu.com/bionic/ubuntu-18.04-live-server-amd64.iso.torrent --verbose
Error: not a number: buffer[0] = 60

UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/webtorrent/webtorrent-cli/issues

DEBUG INFO: webtorrent-cli 1.12.2, webtorrent 0.100.0, node v9.3.0, darwin x64, exit 1
```

**Comment by rom1504** [comment]
I don't think you can pass an url like that to webtorrent. You need to
first download the torrent then give the downloaded file to webtorrent.

**Comment by rom1504** [comment]
Maybe there should be a better error returned by webtorrent in that case
though.

**Comment by mstred** [comment]
I tried later using another network and it was OK:
```bash
$ webtorrent download http://releases.ubuntu.com/bionic/ubuntu-18.04-live-server-amd64.iso.torrent --verbose
verifying existing torrent data...

Downloading: ubuntu-18.04-live-server-amd64.iso
Server running at: http://localhost:8000/0
Downloading to: /Users/edson/Desktop
Speed: 537 KB/s  Downloaded: 2.6 MB/845 MB  Uploaded: 0 B
Running time: 5 seconds  Time remaining: 26 minutes  Peers: 49/82
Queued peers: 413  Blocked peers: 0  Hotswaps: 0
```
Maybe this has something related to network usage blocked for torrent-based protocol applications.

**Comment by metacomgd** [comment]
Had a similar error in peerflix, turned out the URL was intercepted by cloudflare, and hence the "torrent" was a redirect page.
