### ISSUE TITLE
UNEXPECTED ERROR 

### ISSUE THREAD

**Issue by TheObserver42** [webtorrent/webtorrent-cli#54]
~$ webtorrent download https://proxyship.click/torrent/8648434/Fast_And_Furious_6_2013_WebDL_Xvid-OlFa --mpv
Error: not a number: buffer[0] = 60

UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/webtorrent/webtorrent-cli/issues

DEBUG INFO: webtorrent-cli 1.11.0, webtorrent 0.98.20, node v9.2.1, linux x64, exit 1
I don't understand. Why doesn't work ?

**Comment by rom1504** [comment]
You need to download the torrent first then pass the local file to
webtorrent cli

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement. No one will be able to assist you.
