### ISSUE TITLE
Passing `--chromecast` plays to every chromecast on the network

### ISSUE THREAD

**Issue by alexframe** [webtorrent/webtorrent-cli#57]
### Feature proposal

When you pass the `--chromecast` flag, it currently queries and plays to all chromecast on the network.

It would be nice to allow to pass the name of a chromecast device on the network and play to a specific one.

Is this a piece of work that would be welcomed?

**Comment by iovis9** [comment]
Yes, it would definitely be very welcomed!

**Comment by OvermindDL1** [comment]
All 6 chromecasts started playing at home!  That was such a mess!  ^.^;

Any chance on a fix?  This has been a long-time broken...

**Comment by iovis9** [comment]
There's a PR in progress! https://github.com/webtorrent/webtorrent-cli/pull/58

I'd review it but I have no chromecasts unfortunately
