### ISSUE TITLE
Error when seeding

### ISSUE THREAD

**Issue by vsystech** [webtorrent/webtorrent-cli#62]
Hello, i'm create own tracker with webtorrent-tracker, try seed file with command line or webtorrent-webui app but not working. 

UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/webtorrent/webtorrent-cli/issues

DEBUG INFO: webtorrent-cli 1.11.0, webtorrent 0.98.24, node v9.9.0, linux x64, exit 1
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:844:14)
Emitted 'error' event at:
    at Socket.onerror (/usr/lib/node_modules/webtorrent-hybrid/node_modules/readable-stream/lib/_stream_readable.js:640:52)
    at Socket.emit (events.js:180:13)
    at onwriteError (_stream_writable.js:427:12)
    at onwrite (_stream_writable.js:449:5)
    at _destroy (internal/streams/destroy.js:39:7)
    at Socket._destroy (net.js:548:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:846:10)
root@debian-2gb-nbg1-dc3-2 ~ # webtorrent-hybrid seed asdasd.mp4 --announce ws://**.***.***.***:8000/announce

**Comment by DiegoRBaquero** [comment]
will it work in node lts?

**Comment by vsystech** [comment]
sorry, how you think ?

**Comment by vsystech** [comment]
i'm try with webtorrent-hybrid-webui, and webtorrent-hybrid

          "host": "wss://tracker.openwebtorrent.com",
          "lastScrapeResult": "Could not connect to tracker",

          "host": "wss://tracker.fastcast.nz",
          "id": 0,
          "isBackup": false,
          "lastAnnouncePeerCount": 11,
          "lastAnnounceResult": "Success",
          "lastAnnounceStartTime": 1500806166,
          "lastAnnounceSucceeded": true,
          "lastAnnounceTime": 1500806166,
          "lastAnnounceTimedOut": false,
          "lastScrapeResult": "Could not connect to tracker",

**Comment by feross** [comment]
It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.

**Comment by VictorV96** [comment]
Same problem
