### ISSUE TITLE
Detect portable VLC

### ISSUE THREAD

**Issue by souravndp** [webtorrent/webtorrent-cli#63]
It seems that in Windows platform, WebTorrent gets the VLC path from the registry. Is there any way to make it work if I add the VLC location to the environment variable 'PATH'?

I actually don't want to install VLC. I just want to use the portable VLC.

**Comment by DiegoRBaquero** [comment]
It should work if you do add it. Please test adding the location to the env var.

**Comment by DiegoRBaquero** [comment]
It seems that `vlc-command` doesn't use the env var at all. See https://github.com/feross/vlc-command/blob/master/index.js

**Comment by souravndp** [comment]
Yes. vlc-command doesn't use env var. That's why I wonder, whether webtorrent-cli uses it or not? Because in one issue regarding VLC not found, Feross told the OP to troubleshoot using vlc-command tool.

From my second screenshot, you can see that webtorent-cli is unable to detect VLC even if the location is added in the path.

**Comment by DiegoRBaquero** [comment]
It does not. Won’t work even if you add it

**Comment by DiegoRBaquero** [comment]
You should create an issue here: https://github.com/feross/vlc-command

:)

**Comment by souravndp** [comment]
I think you misunderstood me. My main problem is that webtorrent-cli is not detecting portable VLC even if the location is set in the 'Path' environment variable (Windows). I searched Google and came upon an issue (different issue regarding VLC not found) and noticed that Feross told the OP to troubleshoot using vlc-command. I used it and noticed that it also failed to detect VLC. I then suspected that both of them uses the same algorithm to detect VLC (ie, search the registry for install directory). I then manually created the registry key HKLM/Software/VideoLAN/VLC/ (InstallDir= "portable VLC location") and both of them (webtorrent-cli and vlc-command) detected VLC.

So, I am almost sure that in case of windows, webtorretnt-cli only checks the registry, not the path environment variable. Maybe in Linux, it checks env variable but not in windows. That's why I opened the issue here. :)

**Comment by iovis9** [comment]
Diego told you to open an issue there because that's the package we use to determine which VLC binary to use, this is not a webtorrent-cli issue.

**Comment by souravndp** [comment]
ohhh...I didn't know that. I will open a feature request there. Thank you :)

**Comment by iovis9** [comment]
No problem man, hope it gets solved soon!
