### ISSUE TITLE
How can i seed downloaded filed for instant.io using webtorrent-cli

### ISSUE THREAD

**Issue by sangnar** [webtorrent/webtorrent-cli#71]
ubuntu 16.04 / nodejs 8 / webtorrent cli

i download a movie file via bittorrent seeding file
using below command line

webtorrent "magnet:?xt=urn:btih:0f7bc8453d143159220d691e92ffbe7b81c0fdc0" --keep-seeding --quiet

webtorrent is seeding 46255 port and it open.

file download complete but instant.io can't download and stream video from magnet:?xt=urn:btih:0f7bc8453d143159220d691e92ffbe7b81c0fdc0

what can i do for stream video?

**Comment by SilentBot1** [comment]
Hey @sangnar,

[WebTorrent-cli](https://github.com/webtorrent/webtorrent-cli) only supports TCP/UDP peers in the command line, [WebTorrent-hybrid](https://github.com/webtorrent/webtorrent-hybrid) supports both WebRTC and TCP/UDP peers from the command line.

Please don't use WebTorrent for piracy. We cannot help further with this issue.
