### ISSUE TITLE
Chromecast controls?

### ISSUE THREAD

**Issue by tigew** [webtorrent/webtorrent-cli#73]
Is there anyway to control the stream pause/play when going to a chrome cast?

**Comment by tigew** [comment]
I apologize for my pointless question.

**Comment by SilentBot1** [comment]
Hey @tigew, 

The question isn't pointless, it will help others looking for the same answer at a later time :)

The library used to add Chromecast support is [chromecasts](https://www.npmjs.com/package/chromecasts), this library has the ability to play, pause, seek and select subtitle tracks but currently it appears none of this functionality has been implemented into webtorrent-cli, the current implementation can be seen [here](https://github.com/webtorrent/webtorrent-cli/blob/master/bin/cmd.js#L493).

Hope this answers your question.
