### ISSUE TITLE
Cannot seed torrent created from folder with webtorrent cli

### ISSUE THREAD

**Issue by ahundt** [webtorrent/webtorrent-cli#77]
This issue is related to and run on the same setup as:
https://github.com/webtorrent/webtorrent/issues/1417

Here I created a simple example with a single 50MB file in `~/Downloads/test_dataset/file.h5f`

I then ran:
`webtorrent create ~/Downloads/test_dataset/ --private -o ~/Downloads/test_dataset.torrent`

This appeared to create the torrent file successfully.

I then tried 
1. `webtorrent seed test_dataset.torrent`
2. `webtorrent seed ~/Downloads/test_dataset`
3. `webtorrent seed ~/Downloads/test_dataset.torrent`

I also copied the `test_dataset.torrent file` into `~/Downloads/test_dataset` switched to the test_dataset directory, and ran 
4. `webtorrent seed test_dataset.torrent`

None of these allowed the torrent to appear on another machine, and all but 2 indicated 0/50MB was downloaded.

5. `cd ~/Downloads && webtorrent seed test_dataset.torrent` resulted in the following:

```

torrent downloaded successfully from 0/0 peers in 0s!

webtorrent is exiting...

```
Not ideal when I'm trying to seed!

The following command appeared to actually start seeding:
6. `cd ~/Downloads && webtorrent seed test_dataset.torrent --keep-seeding`

I then saw the following output:
```
Seeding: test_dataset
Info hash: [hash edited out]
Server running at: http://localhost:8000/0
Downloading to: ~/Downloads
Speed: 0 B/s  Downloaded: 50 MB/50 MB  Uploaded: 0 B
Running time: 6 minutes  Time remaining: N/A  Peers: 0/0
```

However when I copied the torrent file to another machine on the same network and ran `webtorrent download test_dataset.torrent` no other seeders could be found.

I'm at a university so there may be blocking going on, but I was able to download and watch the video on https://webtorrent.io/ which is why I decided to give webtorrent a try, then ran into the issues above without much error feedback.

**Comment by rom1504** [comment]
Are you sure the --private flag does what you want ?

**Comment by rom1504** [comment]
Well what do you want to do ?

**Comment by ahundt** [comment]
not seed publicly yet, only to those whom I gave the torrent. I guess it might mean only use private trackers or something?

Would that flag have caused the behavior I saw?

**Comment by vaguiners** [comment]
i have the saame problem even without --private flag

**Comment by feross** [comment]
So, there's a bit of a misunderstanding of the commands here. `webtorrent create /my/path` will create a torrent file for the contents of `/my/path`. That part is correct.

But when you use `webtorrent seed /my/path2`, you're actually creating a torrent for `/my/path2` and seeding the files there. So you don't want to run `webtorrent seed somefile.torrent` as then you'll be seeding the torrent file itself.

Your `webtorrent seed ~/Downloads/test_dataset` command is the right one to use.

But you have another problem, which is that you used `--private` when you created the initial torrent file, but not when you were seeding, so you ended up creating a *different* torrent file. You need to use consistent flags. I recommend not using `--private` as that just prevents the use of the DHT to find peers, which is not what you want.

Hope this helps!

**Comment by VictorV96** [comment]
Hello. This instruction does not work for me as for the author, even without --private in the latest version.

And also the code below does not work ... instant.io does not see the link.

const WebTorrent = require('webtorrent-hybrid')

const client = new WebTorrent()
const filePath = __filename

console.log('filePath:', filePath)

client.seed(filePath, torrent => {
  console.log('torrentId (info hash):', torrent.infoHash)
  // console.log('torrentId (magnet link):', torrent.magnetURI)
})
