### ISSUE TITLE
Compiled binary for linux please

### ISSUE THREAD

**Issue by vaguiners** [webtorrent/webtorrent-cli#80]
Is just a pain to compile by yourself

**Comment by SilentBot1** [comment]
@vaguiners,

Installing WebTorrent-cli should be as simple as running `npm install webtorrent-cli -g` with Node installed.

Were you facing errors during this process?

**Comment by vaguiners** [comment]
```
node /usr/lib/node_modules/webtorrent-cli/bin/cmd.js

/usr/lib/node_modules/webtorrent-cli/bin/cmd.js:173
    let torrentId = argv._[1]
    ^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
```

**Comment by vaguiners** [comment]
npm install webtorrent-cli -g

make: Entering directory `/usr/lib/node_modules/webtorrent-cli/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/utf-8-validate/build'
  CC(target) Release/obj.target/validation/src/validation.o
../src/validation.c:2:22: warning: node_api.h: No such file or directory
../src/validation.c:4: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IsValidUTF8'
../src/validation.c:77: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Init'
../src/validation.c:87: warning: return type defaults to 'int'
../src/validation.c: In function 'NAPI_MODULE':
../src/validation.c:87: warning: type of 'NODE_GYP_MODULE_NAME' defaults to 'int'
../src/validation.c:87: warning: type of 'Init' defaults to 'int'
../src/validation.c:87: error: expected '{' at end of input
make: *** [Release/obj.target/validation/src/validation.o] Error 1
make: Leaving directory `/usr/lib/node_modules/webtorrent-cli/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/utf-8-validate/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-042stab127.2
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/webtorrent-cli/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/utf-8-validate
gyp ERR! node -v v0.10.48
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@5.0.1
make: Entering directory `/usr/lib/node_modules/webtorrent-cli/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/bufferutil/build'
  CC(target) Release/obj.target/bufferutil/src/bufferutil.o
../src/bufferutil.c:2:22: warning: node_api.h: No such file or directory
../src/bufferutil.c:4: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Mask'
../src/bufferutil.c:84: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Unmask'
../src/bufferutil.c:150: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'Init'
../src/bufferutil.c:170: warning: return type defaults to 'int'
../src/bufferutil.c: In function 'NAPI_MODULE':
../src/bufferutil.c:170: warning: type of 'NODE_GYP_MODULE_NAME' defaults to 'int'
../src/bufferutil.c:170: warning: type of 'Init' defaults to 'int'
../src/bufferutil.c:170: error: expected '{' at end of input
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
make: Leaving directory `/usr/lib/node_modules/webtorrent-cli/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/bufferutil/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-042stab127.2
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/webtorrent-cli/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/bufferutil
gyp ERR! node -v v0.10.48
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@4.0.0
/usr/bin/webtorrent -> /usr/lib/node_modules/webtorrent-cli/bin/cmd.js
npm WARN unmet dependency /usr/lib/node_modules/block-stream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/fstream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/fstream-ignore requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/fstream-npm requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/glob requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/npmconf requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/tar requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined

**Comment by DiegoRBaquero** [comment]
Please install node 6+

**Comment by SilentBot1** [comment]
@vaguiners,

What node version are you running?

**Comment by rom1504** [comment]
"ERR! node -v v0.10.48"
