### ISSUE TITLE
usage for seeding lots of torrent files

### ISSUE THREAD

**Issue by chovy** [webtorrent/webtorrent-cli#81]
I have a lot of .torrent files in ./torrents/todo

i want the files to download and save to ./torrents/done and keep seeding.

how do I do this?

I tried `webtorrent-hybrid seed ./todo/ -o ./done/ --keep-seeding` but it looks like its only seeding one file with no progress. Also what ports do I need to allow?

**Comment by SilentBot1** [comment]
Hi @chovy 

Currently [webtorrent-cli](https://github.com/webtorrent/webtorrent-cli/) doesn't support seeding multiple torrents in a single instance. To achieve what you're attempting you would either need to open multiple [webtorrent-cli](https://github.com/webtorrent/webtorrent-cli/) instances or merge the individual torrents into one larger torrents for distribution.

If you would like to transition this ticket into a feature request, please re-open the issue and let the team know.

Kind regards
Brad

**Comment by thenikin** [comment]
Hello, 

This looks like a useful feature. Any update regarding this? I'll be checking the code to see if we can manage to create a pull request adding this

Best,
Nicolas
