### ISSUE TITLE
can not get magent url peers

### ISSUE THREAD

**Issue by tolerious** [webtorrent/webtorrent-cli#87]
run `webtorrent webtorrent_uri` in terminal, but it can not find any peer for a long time, then  I copy the uri in other torrent client, it can be downloaded. why?
run `webtorrent info` command the `announce`  and `urlList` are empty.

**Comment by DiegoRBaquero** [comment]
Is this a TCP/UDP shared torrent? Or using a WebRTC one?

Can you share the magnet?

**Comment by tolerious** [comment]
@DiegoRBaquero , sure,  I just run `webtorrent info 'magnet:?xt=urn:btih:47aa0b6d3bed7132d6a53201184113a464fce3b5&dn=[AnimeRG] My Hero Academia (Complete Season 01) Boku no Hero Academia [1080p] [x265] [pseudo]'` command

**Comment by nitnk9** [comment]
You have to run 
```
webtorrent download magnet_uri
```
"dowload is required"

**Comment by SilentBot1** [comment]
Hi @tolerious 

We don't advocate the use of [webtorrent](https://github.com/webtorrent/webtorrent) or it's associated modules for copyright infringement. 

Because of the content of this request, I'm going to close this issue.

Kind regards
Brad
