### ISSUE TITLE
Seeding won't work

### ISSUE THREAD

**Issue by nitnk9** [webtorrent/webtorrent-cli#89]
on seeding:
```
Seeding: localhost.sql
Info hash: e37a3144c5f5c31534d55209fc1a100aee820adf
Speed: 0 B/s  Downloaded: 17 KB/17 KB  Uploaded: 0 B
Running time: 222 seconds  Time remaining: N/A  Peers: 0/0
```

on trying to download the same:

```
webtorrent download e37a3144c5f5c31534d55209fc1a100aee820adf
fetching torrent metadata from 0 peers
```

on same machine as well as different machines.

**Comment by nitnk9** [comment]
webtorrent-hybrid cli works perfectly..

**Comment by mogwai** [comment]
Neither works for me

**Comment by rom1504** [comment]
Great effort to provide as much details a possible went into your assistance request @mogwai
You surely will get help that way.

**Comment by mogwai** [comment]
I'll follow through the steps that I made in a attempt to transfer a file between 2 machine using the cli. They are identical to the original issue:

I tried this on the hybrid version as well.

Seeding Machine (Ubuntu 18.04)

`touch example && echo example >> example`
`webtorrent seed asda`

```
Info hash: 0744ffb7b4362c394761fe0f3efd8a7986a154e1
Speed: 0 B/s  Downloaded: 11 B/11 B  Uploaded: 0 B
Running time: 10 seconds  Time remaining: N/A  Peers: 0/0
```

Recieving Machine (Mac OSx)

`webtorrent download 0744ffb7b4362c394761fe0f3efd8a7986a154e1`
```
(node:2244) Warning: N-API is an experimental feature and could change at any time.
fetching torrent metadata from 0 peer
```

This message persists indefinitely. 

I've noticed that starting the download before the seeding works but this means you have to seed first, stop seeding, start the download with the generated hash and then start seeding again.

**Comment by VictorV96** [comment]
Same problem

**Comment by IamStefin** [comment]
Same
