### ISSUE TITLE
support ed2k?thanks

### ISSUE THREAD

**Issue by hktalent** [webtorrent/webtorrent-cli#97]
webtorrent download 'ed2k://|file|en_windows_xp_professional_with_service_pack_3_x86_cd_x14-80428.iso|617756672|2A30BB63730F7887E1AC54363A8489C2|/'
Error: Invalid torrent identifier

UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/webtorrent/webtorrent-cli/issues

DEBUG INFO: webtorrent-cli 1.12.3, webtorrent 0.103.1, node v10.12.0, linux x64, exit 1

**Comment by SilentBot1** [comment]
Hi @hktalent 

I believe that this is outside of the scope of the [webtorrent-cli](https://github.com/webtorrent/webtorrent-cli/) module and wouldn't fit well within the [webtorrent](https://github.com/webtorrent/webtorrent/) library. You would be best using an already existing ed2k client such as [AMule](http://wiki.amule.org/wiki/AMule) and it's provided command line [documentation](http://wiki.amule.org/wiki/Ed2k_command).

If you disagree with this decision, please feel free to re-open the issue.

Kind regards
Brad
